#!/usr/bin/env python3.10

from exceptions import ApiServiceError, CantGetCoordinates
from gps_coordinates import get_gps_coordinates
from weather_api_service import get_weather
from weather_formatter import format_weather


def main():
    try:
        coordinates = get_gps_coordinates()
    except CantGetCoordinates as e:
        print("Не смог получить координаты", f"({e.msg})")
        exit(1)

    try:
        weather = get_weather(coordinates)
    except ApiServiceError as e:
        print("Не смог получить данные от API сервиса погоды", f"({e.msg})")
        exit(1)
        
    print(format_weather(weather))


if __name__ == "__main__":
    main()
